

GET http://localhost:3000/cars/1


###

GET http://localhost:3000/cars


###

POST http://localhost:3000/cars
Content-Type: application/json

{
  "make": "Honda",
  "model": "Accord", 
  "color": "Navy"
}

###

PATCH http://localhost:3000/cars/4
Content-Type: application/json

{
  "make": "Dodge",
  "model": "Test", 
  "color": "Red"
}